version: '3'
services:
  django_api:
    build: .
    image: lakau/django_api
    container_name: django_api
    ports:
      - '8030:8030'
    links:
      - db
  db:
    build: db/.
    image: lakau/psql
    container_name: db
    ports:
      - '5432:5432'

