version: '3'
services:
  api:
    build: .
    image: api
    container_name: api
    command: pipenv run uwsgi --ini uwsgi.ini
    ports:
      - '80:80'
    depends_on:
      - db
  db:
    build: db/.
    image: psql
    container_name: db
    ports:
      - '5432:5432'
