version: '3'
services:
  nginx:
    build: nginx/.
    image: irsyadmhdilham/django-static
    container_name: nginx-static
    depends_on:
      - api
    volumes:
      - static-assets:/django_app/static
      - uploads-assets:/django_app/uploads
    ports:
      - '8200:8200'
  api:
    build: .
    image: irsyadmhdilham/api
    container_name: api
    command: pipenv run uwsgi --ini uwsgi.ini
    ports:
      - '8100:8100'
    volumes:
      - static-assets:/django_app/static
      - uploads-assets:/django_app/uploads
    depends_on:
      - psql
  psql:
    build: postgres/.
    image: irsyadmhdilham/psql
    container_name: psql
    ports:
      - '5432:5432'
volumes:
  static-assets:
  uploads-assets: