version: '3'
services:
  django_api:
    build: .
    image: django_api
    container_name: django_api
    command: gunicorn --workers=4 -b :8030 django_app.wsgi
    ports:
      - '8030:8030'
    depends_on:
      - db
  db:
    build: db/.
    image: psql
    container_name: db
    ports:
      - '5432:5432'
