# Generated by Django 2.1.2 on 2018-12-19 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('point', models.IntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.PointField')),
            ],
        ),
        migrations.CreateModel(
            name='PointLogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='point',
            name='logs',
        ),
        migrations.AddField(
            model_name='pointlog',
            name='point_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.PointLogType'),
        ),
        migrations.AddField(
            model_name='point',
            name='logs',
            field=models.ManyToManyField(related_name='logs', to='apis.PointLog'),
        ),
    ]
