# Generated by Django 2.1.2 on 2018-11-13 15:49

import apis._models.profile
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=apis._models.profile.default_settings),
        ),
    ]
