# Generated by Django 2.1.2 on 2019-02-20 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='reminder',
        ),
    ]
