# Generated by Django 2.1.2 on 2019-01-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_auth',
            field=models.BooleanField(default=False),
        ),
    ]
