# Generated by Django 2.1.2 on 2018-12-19 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_type',
            field=models.ForeignKey(default='Personal', on_delete=django.db.models.deletion.CASCADE, to='apis.ChatType', to_field='name'),
        ),
    ]
