# Generated by Django 2.1.2 on 2019-03-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
