# Generated by Django 2.1.2 on 2018-12-19 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20181219_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_owner', to='apis.Profile'),
        ),
    ]
