# Generated by Django 2.1.2 on 2019-03-14 02:56

import apis._models.memo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_sales_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='start_date',
        ),
        migrations.AddField(
            model_name='memo',
            name='expiry_date',
            field=models.DateTimeField(default=apis._models.memo.expiry_date),
        ),
    ]
