# Generated by Django 2.1.2 on 2019-02-05 06:22

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_profile_call_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='call_logs',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, default=list, size=None),
        ),
    ]
