# Generated by Django 2.1.2 on 2018-12-19 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20181219_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.Agency'),
        ),
    ]
