# Generated by Django 2.1.2 on 2019-02-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_schedule_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='call_logs',
        ),
    ]
