# Generated by Django 2.1.2 on 2018-12-20 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20181220_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='members',
            field=models.ManyToManyField(related_name='agencies', to='apis.Profile'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='apis.Schedule'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups', to='apis.Profile'),
        ),
        migrations.AlterField(
            model_name='point',
            name='attributes',
            field=models.ManyToManyField(related_name='points', to='apis.PointAttribute'),
        ),
        migrations.AlterField(
            model_name='post',
            name='users_tagged',
            field=models.ManyToManyField(blank=True, related_name='posts', to='apis.Profile'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.Contact'),
        ),
    ]
