# Generated by Django 2.1.2 on 2019-03-15 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20190314_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.ContactType'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.ForeignKey(default='None', null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.ContactStatus', to_field='name'),
        ),
    ]
