# Generated by Django 2.1.2 on 2018-12-27 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_notification_inbox_rel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='group_chat',
        ),
        migrations.AddField(
            model_name='inbox',
            name='group_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.GroupChat'),
        ),
    ]
