# Generated by Django 2.1.2 on 2019-02-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20190205_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='call_logs',
        ),
    ]
