# Generated by Django 2.1.2 on 2018-11-14 04:26

import apis._models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20181114_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='/Users/lakau/Documents/squalify/apis/django_app/uploads/no_image.jpeg', upload_to=apis._models.profile.user_directory_path),
        ),
    ]
