# Generated by Django 2.1.2 on 2018-12-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20181220_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='chat',
            new_name='chats',
        ),
    ]
