# Generated by Django 2.1.2 on 2019-01-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20181227_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
