# Generated by Django 2.1.2 on 2019-02-05 08:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_remove_profile_call_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='call_logs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
