# Generated by Django 2.1.2 on 2019-01-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_profile_wisdoms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='wisdoms',
            new_name='words',
        ),
    ]
