# Generated by Django 2.1.2 on 2019-01-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_googleapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleapi',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
