# Generated by Django 2.1.2 on 2019-02-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_profile_call_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
