# Generated by Django 2.1.2 on 2019-01-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20190128_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tips',
            field=models.TextField(blank=True, null=True),
        ),
    ]
