# Generated by Django 2.1.2 on 2018-12-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20181220_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='chats',
            new_name='chat',
        ),
    ]
