# Generated by Django 2.1.2 on 2019-03-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20190327_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalledVia',
            new_name='ContactVia',
        ),
        migrations.RenameField(
            model_name='calllog',
            old_name='called_via',
            new_name='contact_via',
        ),
    ]
