# Generated by Django 2.1.2 on 2018-11-14 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20181114_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.Agency'),
        ),
    ]
