# Generated by Django 2.1.2 on 2019-02-13 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactstatus',
            old_name='status',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contacttype',
            old_name='contact_type',
            new_name='name',
        ),
    ]
