# Generated by Django 2.1.2 on 2018-11-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20181114_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_image',
            field=models.ImageField(default='/Users/lakau/Documents/squalify/apis/django_app/assets/no_image.jpeg', upload_to='assets/agencies'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='agency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apis.Agency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='/Users/lakau/Documents/squalify/apis/django_app/assets/no_image.jpeg', upload_to='assets'),
        ),
    ]
