# Generated by Django 2.1.2 on 2018-12-20 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20181220_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_type',
        ),
        migrations.AddField(
            model_name='inbox',
            name='chat_type',
            field=models.ForeignKey(default='Personal', on_delete=django.db.models.deletion.CASCADE, to='apis.ChatType', to_field='name'),
        ),
    ]
