# Generated by Django 2.1.2 on 2019-03-02 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20190228_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='date_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='memo',
            old_name='date_start',
            new_name='start_date',
        ),
    ]
