# Generated by Django 2.1.2 on 2019-03-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20190327_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllog',
            name='contact_via',
        ),
        migrations.AlterField(
            model_name='contactvia',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
