# Generated by Django 2.1.2 on 2018-12-20 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_auto_20181220_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='chat_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_with', to='apis.Profile'),
        ),
    ]
