# Generated by Django 2.1.2 on 2019-01-30 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_groupchat_group_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='role',
        ),
        migrations.DeleteModel(
            name='GroupChatRole',
        ),
    ]
