# Generated by Django 2.1.2 on 2018-12-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_inbox_chat_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='unread',
            field=models.IntegerField(default=0),
        ),
    ]
