# Generated by Django 2.1.2 on 2019-03-05 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_auto_20190305_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Surcharge',
        ),
    ]
