# Generated by Django 2.1.2 on 2019-01-30 13:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_auto_20190130_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
