# Generated by Django 2.1.2 on 2018-11-15 22:58

import apis._models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_auto_20181115_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_image',
            field=models.ImageField(default='no_image.jpeg', upload_to='agencies'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='no_image.jpeg', upload_to=apis._models.profile.user_directory_path),
        ),
    ]
