# Generated by Django 2.1.2 on 2018-12-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_inbox_unread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='unread',
            field=models.IntegerField(default=1),
        ),
    ]
