# Generated by Django 2.1.2 on 2019-03-06 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_delete_surcharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='memo',
        ),
        migrations.AddField(
            model_name='agency',
            name='memos',
            field=models.ManyToManyField(blank=True, to='apis.Memo'),
        ),
        migrations.AddField(
            model_name='memo',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.Profile'),
        ),
        migrations.AddField(
            model_name='memo',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
