# Generated by Django 2.1.2 on 2019-02-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_auto_20190130_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tips',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='words',
        ),
    ]
