# Generated by Django 2.1.2 on 2019-04-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_schedule_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='tips',
            field=models.TextField(blank=True, null=True),
        ),
    ]
