# Generated by Django 2.1.2 on 2018-12-21 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_auto_20181221_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(to='apis.ChatMessage')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.Profile')),
                ('participants', models.ManyToManyField(blank=True, related_name='chats', to='apis.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='composed_by',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='chat_type',
        ),
        migrations.AddField(
            model_name='inbox',
            name='messages',
            field=models.ManyToManyField(to='apis.ChatMessage'),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatType',
        ),
        migrations.AddField(
            model_name='inbox',
            name='group_chat',
            field=models.ManyToManyField(blank=True, to='apis.GroupChat'),
        ),
    ]
