# Generated by Django 2.1.2 on 2019-03-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_auto_20190306_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='countdown',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
