# Generated by Django 2.1.2 on 2018-11-19 11:53

import apis._models.agency
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_auto_20181115_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.Contact'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_image',
            field=models.ImageField(default='no_image.jpeg', upload_to=apis._models.agency.agency_directory_path),
        ),
    ]
