# Generated by Django 2.1.2 on 2019-04-11 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_sales_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='memo_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.Memo'),
        ),
    ]
