# Generated by Django 2.1.2 on 2019-03-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_auto_20190306_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='comments',
            field=models.ManyToManyField(blank=True, to='apis.Comment'),
        ),
        migrations.AddField(
            model_name='memo',
            name='likes',
            field=models.ManyToManyField(blank=True, to='apis.Like'),
        ),
    ]
