# Generated by Django 2.1.2 on 2018-11-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_auto_20181119_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='repetition',
            new_name='reminder',
        ),
    ]
