# Generated by Django 2.1.2 on 2018-12-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_auto_20181221_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='messages',
            field=models.ManyToManyField(blank=True, to='apis.ChatMessage'),
        ),
    ]
