# Generated by Django 2.1.2 on 2019-02-02 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_auto_20190202_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='api_token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.Token'),
        ),
    ]
