# Generated by Django 2.1.2 on 2018-12-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_auto_20181224_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='messages',
            field=models.ManyToManyField(blank=True, to='apis.ChatMessage'),
        ),
    ]
