# Generated by Django 2.1.2 on 2018-11-20 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_auto_20181119_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='apis.Contact'),
        ),
    ]
