# Generated by Django 2.1.2 on 2018-11-22 04:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_auto_20181120_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='point',
            name='agency_program',
        ),
        migrations.RemoveField(
            model_name='point',
            name='appointment_secured',
        ),
        migrations.RemoveField(
            model_name='point',
            name='be_early_training',
        ),
        migrations.RemoveField(
            model_name='point',
            name='calls_emails_socmed',
        ),
        migrations.RemoveField(
            model_name='point',
            name='career_presentation',
        ),
        migrations.RemoveField(
            model_name='point',
            name='case_closed',
        ),
        migrations.RemoveField(
            model_name='point',
            name='ftf_booth_nesting',
        ),
        migrations.RemoveField(
            model_name='point',
            name='joining_field_work',
        ),
        migrations.RemoveField(
            model_name='point',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='point',
            name='millionnaire_suit',
        ),
        migrations.RemoveField(
            model_name='point',
            name='personal_coaching',
        ),
        migrations.RemoveField(
            model_name='point',
            name='referrals',
        ),
        migrations.RemoveField(
            model_name='point',
            name='sales_presentation',
        ),
        migrations.RemoveField(
            model_name='point',
            name='servicing_follow_up',
        ),
        migrations.RemoveField(
            model_name='point',
            name='sign_up_contract',
        ),
        migrations.RemoveField(
            model_name='point',
            name='update_upline',
        ),
        migrations.AddField(
            model_name='point',
            name='logs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pointattribute',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.PointField'),
        ),
        migrations.AddField(
            model_name='point',
            name='point',
            field=models.ManyToManyField(related_name='points', to='apis.PointAttribute'),
        ),
    ]
