# Generated by Django 2.1.2 on 2018-12-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_auto_20181224_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
