# Generated by Django 2.1.2 on 2018-12-24 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_groupchatrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.GroupChatRole'),
            preserve_default=False,
        ),
    ]
