# Generated by Django 2.1.2 on 2018-11-22 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_auto_20181122_0401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointattribute',
            old_name='field',
            new_name='point_attr',
        ),
    ]
