# Generated by Django 2.1.2 on 2018-11-22 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_auto_20181122_0426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='point',
            new_name='points',
        ),
    ]
