# Generated by Django 2.1.2 on 2018-11-22 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_auto_20181122_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointattribute',
            old_name='timestamp',
            new_name='last_modified',
        ),
    ]
