# Generated by Django 2.1.2 on 2018-11-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_auto_20181123_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='points',
        ),
        migrations.AddField(
            model_name='point',
            name='attributes',
            field=models.ManyToManyField(related_name='attributes', to='apis.PointAttribute'),
        ),
    ]
