# Generated by Django 2.1.2 on 2018-11-26 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0020_auto_20181125_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('likers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='applause',
            name='applausers',
        ),
        migrations.RenameField(
            model_name='posttype',
            old_name='post_type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='applause',
        ),
        migrations.DeleteModel(
            name='Applause',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, to='apis.Like'),
        ),
    ]
