# Generated by Django 2.1.2 on 2018-11-29 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0022_auto_20181128_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='likers',
            new_name='liker',
        ),
    ]
