# Generated by Django 2.1.2 on 2018-11-30 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0023_auto_20181129_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='schedule',
            new_name='schedules',
        ),
    ]
