# Generated by Django 2.1.2 on 2018-12-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0024_auto_20181130_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='designation',
            old_name='designation',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='industry',
            old_name='industry',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='group',
            name='company',
        ),
        migrations.RemoveField(
            model_name='group',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='group',
            name='owner',
        ),
    ]
