# Generated by Django 2.1.2 on 2018-12-03 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0025_auto_20181203_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='owner',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='agency_owner', to='apis.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='apis.Profile'),
            preserve_default=False,
        ),
    ]
